name: update-osebx

on:
  schedule:
    - cron: "15 12 * * 1-5"   # Weekdays ~12:15 UTC; adjust as you like
  workflow_dispatch: {}       # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch OSEBX
        run: python scripts/osebx_fetch.py

      - name: Commit & push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/osebx.json
          git commit -m "Update OSEBX time series" || echo "No changes to commit"
          git push

