name: Portfolio Builder
permissions:
  contents: write   # allow pushing generated JSON/CSV back to the repo

on:
  schedule:
    - cron: "5,35 * * * *"   # run at :05 and :35, i.e., 5 minutes after a :00/:30 scan
  workflow_dispatch:          # also allow manual runs from the Actions tab

jobs:
  build_portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build portfolio files
        run: |
          python portfolio_builder.py

      - name: Commit and push portfolio data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/portfolio_state.json public/data/portfolio_nav.json public/data/trade_log.csv
          git commit -m "Update portfolio files" || echo "No changes to commit"
          git push
